'use strict';
const modal = document.querySelector('.modal')
const overlay = document.querySelector('.overlay')
const btnCloseModal = document.querySelector('.close-modal')
const btnsOpenModal = document.querySelectorAll('.show-modal')  //will give a list of all the modals
console.log(btnsOpenModal)  

const closeModal = function(){
    modal.classList.add('hidden')
    overlay.classList.add('hidden')  //adds the hidden class to the classList
}

const openModal = function(){
    console.log("button clicked")
    modal.classList.remove('hidden')       //classList is an object attached to every html element that holds a list of classes
    overlay.classList.remove('hidden')     //for modal classlist = ['modal','hidden'], remove is a func we call
}

for(let i = 0; i < btnsOpenModal.length; i++){
    btnsOpenModal[i].addEventListener('click', openModal)
}

//this above loop attaches an eventlistener to each of the modals 

btnCloseModal.addEventListener('click', closeModal) 
overlay.addEventListener('click', closeModal)

document.addEventListener('keydown', function(eve){   //this lisentener listens for event across the entire page
    console.log('A key was pressed')                  //this will call if any key is pressed, even mouse clicks
    console.log(eve)
    console.log(eve.key)  
    if(eve.key === 'Escape'){                        //now we can close the modal even after pressing escape
        if(!modal.classList.contains('hidden')){     //we check if modal already hidden, if not then hide
            closeModal()
        }
    }
})    

/*
in the above two lines we say closeModal and not closeModal() cuz then JS would execute the func as soon as 
it reads the line, but we only want it to execute when the click happens
modal.style.display = 'block'   //this changes style and allows a model to be visible, as a block level element 
keyboard events are global events

keyup: happens when u lift ur finger off the key
keydown: happens as soon as u presss the key
keypress: keeps happening till u have the key pressed

an event object is generated by JS and contains all info about the event whenever it happens
that event obejct is by defualt passed to the function as the first argument if u write some name for the arg 
in the above code we chose the name eve for that event object being passed
*/
    
console.warn("hello")   //makes it look like a warning
console.error("hello") //makes it look like an error
//when u add a breakpoint, u get op for everything in console before that line
